FROM ghcr.io/celestiaorg/celestia-node:latest

USER root

# hadolint ignore=DL3018
RUN apk --no-cache add \
        curl \
        jq \
        openssl \
        netcat-openbsd \
        net-tools \
        bind-tools \
    && mkdir /bridge \
    && chown celestia:celestia /bridge

USER celestia

COPY entrypoint-bridge.sh /opt/entrypoint-bridge.sh

# Expose bridge ports:
# 26658 - Bridge RPC
# 26659 - Bridge Gateway
EXPOSE 26658 26659

ENTRYPOINT [ "/bin/bash", "/opt/entrypoint-bridge.sh" ]
